### ISSUE TITLE
Support fallback to environments

### ISSUE THREAD

**Issue by Anhui-tqhuang** [cloudnative-pg/barman-cloud#59]
barman cli supports reading credentials from environment directly which includes
- azure storage key, connection string, sas token
- azure default credentials chan

but i notice that cloudnative doesn't support that, i have to specify the on of the following credentials in the cnpg specification
- azure storage key, connection string, sas token
- managed identity

it doesn't include service principal like client secret credentials, i am wondering could it be possible to support have something like `environments`  so default credentials could take effect in barman cli

on aws when i set `inheritFromIAMRole`,it will be able to load wither aws_access_key_id & aws_secret_access_key or aws_role_arn & aws_web_identity_token_file env

but on azure if i set `inheritFromAzureAD`, it asks me have to use managed identity, i cannot use servicePrincipal or env listed here

in conclusion, i don't want to inject environment variables to pg pods directly by myself, with one single / dedicated PG manifest like
```yaml
    barmanObjectStore:
      azureCredentials:
        inheritFromAzureAD: false
      data:
        compression: gzip
      destinationPath: https://edbpgai.blob.core.windows.net/edbpgai/edb-internal-backups/a7462dbc7106/databases
      wal:
        compression: gzip
```

currently i will be blocked by the following webhook error
```
spec.backup.barmanObjectStore.azureCredentials: Invalid value: api.AzureCredentials{ConnectionString:(*api.SecretKeySelector)(nil), StorageAccount:(*api.SecretKeySelector)(nil), StorageKey:(*api.SecretKeySelector)(nil), StorageSasToken:(*api.SecretKeySelector)(nil), InheritFromAzureAD:false}: when connection string is not specified, one and only one of storage key and storage SAS token is allowed
```
